### ISSUE TITLE
Lack of clear explanation of functionality

### ISSUE THREAD

**Issue by cdgdigital** [strangerstudios/pmpro-invite-only#11]
This plugin only create Invite Codes, if appropriately customized, when new member does checkout. 
The invite code can be used for that new member to sharing with others.

I need to create INVITE CODEs for specific new users to getting into specific levels of membership.

In other words, I want to send a personalized invitation link for a member to be able to click and register on a specific level and only at that level.

**Comment by kimcoleman** [comment]
Please open a ticket in our Support Area for help generating codes for existing members.

https://www.paidmembershipspro.com/pricing/
