### ISSUE TITLE
Does Not Generate Initial Invite Code

### ISSUE THREAD

**Issue by affiliatenow** [strangerstudios/pmpro-invite-only#3]
When is the initial invite code generated?

Right now after activating and setting the array with the proper ID I see all the new fields in the profile and on the registration page...

None of my users have any invite codes populated. I have created new users, since activating and changed their membership levels... and nothing seems to kick off the generation of the invite codes.

**Comment by deikka** [comment]
I'm in the same page...

**Comment by cdgdigital** [comment]
Same thing here.

**Comment by ideadude** [comment]
Note that the plugin doesn't retroactively add codes to existing users. You can add codes manually on the edit user page. To add codes to existing users in mass, you would have to write a custom script. We can help in the member forums.

Let me know if anyone is still not seeing users given codes when their level changes or at checkout when their level is set in the $pmproio_invite_given_levels global.
